-- MySQL Script generated by MySQL Workbench
-- Fri Feb 17 16:49:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pis_data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pis_data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pis_data` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `pis_data` ;

-- -----------------------------------------------------
-- Table `pis_data`.`attendanceg1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`attendanceg1` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`attendanceg1` (
  `id` INT NOT NULL,
  `Student` INT NOT NULL,
  `Sessions1` TINYINT NOT NULL DEFAULT 0,
  `Sessions2` TINYINT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `attendance_student_foreign_idx` (`Student` ASC) VISIBLE,
  CONSTRAINT `attendance_student_foreign`
    FOREIGN KEY (`Student`)
    REFERENCES `pis_data`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `pis_data`.`attendanceg2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`attendanceg2` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`attendanceg2` (
  `id` INT NOT NULL,
  `Student` INT NOT NULL,
  `Sessions1` TINYINT NOT NULL DEFAULT 0,
  `Sessions2` TINYINT NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `attendance_student_foreign0_idx` (`Student` ASC) VISIBLE,
  CONSTRAINT `attendance_student_foreign0`
    FOREIGN KEY (`Student`)
    REFERENCES `pis_data`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `pis_data`.`batches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`batches` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`batches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Batch` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pis_data`.`degrees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`degrees` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`degrees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Degree` VARCHAR(255) NOT NULL,
  `Faculty` INT UNSIGNED NOT NULL,
  `Department` INT UNSIGNED NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `degree_faculty_foreign_idx` (`Faculty` ASC) VISIBLE,
  INDEX `degree_department_foreign_idx` (`Department` ASC) VISIBLE,
  CONSTRAINT `degree_faculty_foreign`
    FOREIGN KEY (`Faculty`)
    REFERENCES `pis_data`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `degree_department_foreign`
    FOREIGN KEY (`Department`)
    REFERENCES `pis_data`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pis_data`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`departments` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`departments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `Faculty` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `department_faculty_foreign_idx` (`Faculty` ASC) VISIBLE,
  CONSTRAINT `department_faculty_foreign`
    FOREIGN KEY (`Faculty`)
    REFERENCES `pis_data`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pis_data`.`designations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`designations` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`designations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 272
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pis_data`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`employees` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`employees` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Index` VARCHAR(255) NOT NULL,
  `Uid` VARCHAR(255) NULL DEFAULT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Telephone` VARCHAR(20) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  `Department` INT UNSIGNED NOT NULL,
  `Designation` INT UNSIGNED NOT NULL,
  `SalaryCode` INT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Api_token` VARCHAR(80) NULL DEFAULT NULL,
  `Remember_token` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `employees_department_foreign` (`Department` ASC) VISIBLE,
  INDEX `employees_designation_foreign` (`Designation` ASC) VISIBLE,
  INDEX `employees_salarycode_foreign` (`SalaryCode` ASC) VISIBLE,
  CONSTRAINT `employees_department_foreign`
    FOREIGN KEY (`Department`)
    REFERENCES `pis_data`.`departments` (`id`),
  CONSTRAINT `employees_designation_foreign`
    FOREIGN KEY (`Designation`)
    REFERENCES `pis_data`.`designations` (`id`),
  CONSTRAINT `employees_salarycode_foreign`
    FOREIGN KEY (`SalaryCode`)
    REFERENCES `pis_data`.`salary_codes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1177
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pis_data`.`employees_of_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`employees_of_groups` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`employees_of_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Employee` INT UNSIGNED NOT NULL,
  `Group` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `employeegroup_employee_foreign_idx` (`Employee` ASC) VISIBLE,
  INDEX `employeegroup_group_foreign_idx` (`Group` ASC) VISIBLE,
  CONSTRAINT `employeegroup_employee_foreign`
    FOREIGN KEY (`Employee`)
    REFERENCES `pis_data`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employeegroup_group_foreign`
    FOREIGN KEY (`Group`)
    REFERENCES `pis_data`.`student_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pis_data`.`faculties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`faculties` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`faculties` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pis_data`.`groups_for_students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`groups_for_students` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`groups_for_students` (
  `id` INT NOT NULL,
  `Student` INT NOT NULL,
  `Group` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `groupStudent_group_foreign_idx` (`Group` ASC) VISIBLE,
  INDEX `groupStudent_student_foreign_idx` (`Student` ASC) VISIBLE,
  CONSTRAINT `groupStudent_student_foreign`
    FOREIGN KEY (`Student`)
    REFERENCES `pis_data`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `groupStudent_group_foreign`
    FOREIGN KEY (`Group`)
    REFERENCES `pis_data`.`student_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `pis_data`.`medical_forms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`medical_forms` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`medical_forms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Student` INT NOT NULL,
  `Session` INT NOT NULL,
  `Medical_form` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `medical_student_foreign_idx` (`Student` ASC) VISIBLE,
  INDEX `medical_session_foreign_idx` (`Session` ASC) VISIBLE,
  CONSTRAINT `medical_student_foreign`
    FOREIGN KEY (`Student`)
    REFERENCES `pis_data`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `medical_session_foreign`
    FOREIGN KEY (`Session`)
    REFERENCES `pis_data`.`sessions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `pis_data`.`modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`modules` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`modules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Faculty` INT UNSIGNED NOT NULL,
  `Department` INT UNSIGNED NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `module_faculty_foreign_idx` (`Faculty` ASC) VISIBLE,
  INDEX `module_department_foreign_idx` (`Department` ASC) VISIBLE,
  CONSTRAINT `module_faculty_foreign`
    FOREIGN KEY (`Faculty`)
    REFERENCES `pis_data`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `module_department_foreign`
    FOREIGN KEY (`Department`)
    REFERENCES `pis_data`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `pis_data`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`password_resets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pis_data`.`salary_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`salary_codes` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`salary_codes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pis_data`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`sessions` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`sessions` (
  `id` INT NOT NULL,
  `Group` INT NOT NULL,
  `Start_time` TIMESTAMP NOT NULL,
  `Duration` DOUBLE NOT NULL,
  `Method` TINYINT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `Type` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `session_group_foreign_idx` (`Group` ASC) VISIBLE,
  CONSTRAINT `session_group_foreign`
    FOREIGN KEY (`Group`)
    REFERENCES `pis_data`.`student_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `pis_data`.`student_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`student_groups` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`student_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Module` INT NOT NULL,
  `Batch` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `group_module_foreign_idx` (`Module` ASC) VISIBLE,
  INDEX `group_batch_foreign_idx` (`Batch` ASC) VISIBLE,
  CONSTRAINT `group_module_foreign`
    FOREIGN KEY (`Module`)
    REFERENCES `pis_data`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `group_batch_foreign`
    FOREIGN KEY (`Batch`)
    REFERENCES `pis_data`.`batches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `pis_data`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`students` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`students` (
  `id` INT NOT NULL,
  `Index` VARCHAR(255) NOT NULL,
  `Uid` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Telephone` VARCHAR(20) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  `Faculty` INT UNSIGNED NOT NULL,
  `Degree` INT NOT NULL,
  `Batch` INT NOT NULL,
  `Academic_Advisor` INT UNSIGNED NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Api_token` VARCHAR(80) NULL DEFAULT NULL,
  `Remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `students_faculty_foreign` (`Faculty` ASC) VISIBLE,
  INDEX `student_degree_foreign_idx` (`Degree` ASC) VISIBLE,
  INDEX `student_batch_foreign_idx` (`Batch` ASC) VISIBLE,
  INDEX `student_advisor_foreign_idx` (`Academic_Advisor` ASC) VISIBLE,
  CONSTRAINT `students_faculty_foreign`
    FOREIGN KEY (`Faculty`)
    REFERENCES `pis_data`.`faculties` (`id`),
  CONSTRAINT `student_degree_foreign`
    FOREIGN KEY (`Degree`)
    REFERENCES `pis_data`.`degrees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_batch_foreign`
    FOREIGN KEY (`Batch`)
    REFERENCES `pis_data`.`batches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_advisor_foreign`
    FOREIGN KEY (`Academic_Advisor`)
    REFERENCES `pis_data`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6183
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pis_data`.`timetable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pis_data`.`timetable` ;

CREATE TABLE IF NOT EXISTS `pis_data`.`timetable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group` INT NOT NULL,
  `Day` INT UNSIGNED NOT NULL,
  `Start_time` TIMESTAMP NOT NULL,
  `End_time` TIMESTAMP NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `timetable_groups_foreign_idx` (`group` ASC) VISIBLE,
  CONSTRAINT `timetable_groups_foreign`
    FOREIGN KEY (`group`)
    REFERENCES `pis_data`.`student_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
